HASTE_WEBSITE_URL = "https://haste.net"
HASTE_FREE_TRIAL_URL = "https://account.haste.net/my-account/?hm=register"
FAKE_EMAIL_URL = "https://emailfake.com"
RANDOM_WORD_GENERATOR_URL = "https://randomwordgenerator.com"
CHROME_DRIVER_PATH = "chromedriver.exe"
